services:
  stalwart-mail:
    build:
      context: .
    ports:
      - "443"
      - "8080"
      - "25"
      - "587"
      - "465"  
      - "143"
      - "993"
      - "4190"
      - "110"
      - "995"
    volumes:
      - stalwart_data:/opt/stalwart-mail
    restart: unless-stopped

volumes:
  stalwart_data:
